In [1]:
import pickle
import numpy as np

In [2]:
ohe = pickle.load(open('ohe_model.pkl', 'rb'))
clf = pickle.load(open('clf.pkl', 'rb'))

In [25]:
test_input = np.array([2, 'male', 31.0, 0, 10.5, 'S'],dtype=object).reshape(1,6)

In [27]:
test_input[:,1].reshape(1,1),test_input[:,5].reshape(1,1)

(array([['male']], dtype=object), array([['S']], dtype=object))

In [28]:
features_to_encode = np.column_stack((test_input[:, 1], test_input[:, 5]))

In [29]:
test_input_ohe = ohe.transform(features_to_encode)

c:\Users\HOU_User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [30]:
test_input_ohe

array([[0., 1., 0., 0., 1., 0.]])

In [34]:
test_input_transformed = np.concatenate((test_input[:,[0,2,3,4]],test_input_ohe),axis=1)

In [35]:
test_input[:,[0,2,3,4]]

array([[2, 31.0, 0, 10.5]], dtype=object)

In [36]:
test_input_transformed.shape

(1, 10)

In [37]:
clf.predict(test_input_transformed)

array([0])